### ISSUE TITLE
Only handle specific config sections

### ISSUE THREAD

**Issue by jvllmr** [jordantshaw/pydantic-config#15] opened 2023-12-05 08:02 UTC
Hello there,

first of all, thank you for this library. I really wanted to use something like this in my future projects and I probably would have implemented this myself if this was not there.

However, I see room for improvement. For example, when I create a tool which saves its config in the `pyproject.toml` under `[tool.mytool]` it would be great if I can only parse a specific section instead of having to declare an explicit path and models and access it that way.

Let me demonstrate my idea:

```python
from pydantic_config import SettingsModel, SettingsConfig
from pydantic import BaseModel

class MyTool(BaseModel):
    my_config_var: str

class Tool(BaseModel):
    mytool: MyTool

class PyProjectToml(SettingsModel)
    tool: Tool

    model_config = SettingsDict(config_file="pyproject.toml")

```
This solution wold be much more elegant imo:

```python
from pydantic-config import SettingsModel, SettingsConfig

class MyToolConfig(SettingsModel):
    my_config_var: str

    model_config = SettingsDict(config_file="pyproject.toml", section="tool.mytool")

```

**Comment by jordantshaw** [comment] 2023-12-05 15:20
@jvllmr Thanks for the suggestion, I appreciate the feedback and I am always happy to consider new feature requests and contributions.

However I'm not sure that adding a feature to only parse specific sections within a config file is something we want to support. I have not seen any other configuration management packages support this type of behavior either (eg. Dynaconf).

I think the main issue here is you are storing non-package related configurations within the pyproject.toml file.  This file was designed for packaging configuration. I would suggest storing non-packaging related configuration outside of the pyproject.toml file. But I do recognize that it has become more popular than the creators probably originally intended to also store other configurations in the file ([see this post](https://discuss.python.org/t/toml-development-has-stalled-implications-for-pyproject-toml-and-a-way-forward/26521/21)).  

This is something I will continue to evaluate and consider going forward.

**Comment by jvllmr** [comment] 2023-12-05 15:44
Good point. I hardly know any other use-case where a config is in another applications config file. `pyproject.toml` was really not designed for that purpose, but I am one of the people who like the convenience of having my configurations for developer tools all in one place. The only other use-case I could imagine is when you create an ecosystem with multiple apps that have their own configuration sections and you want to decouple your configurations.

**Comment by jordantshaw** [comment] 2024-01-30 03:16
Closing for now as this is probably out of scope for this library.

**Closed** 2024-01-30 03:15 UTC
Labels: enhancement
